# Generated by Django 5.0.4 on 2024-05-07 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField(default=0)),
                ('movie_url', models.CharField(max_length=200)),
                ('trailer_url', models.CharField(max_length=200)),
                ('trailer_thumbnail_url', models.CharField(max_length=200)),
            ],
        ),
    ]
