# Generated by Django 5.0.4 on 2024-05-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(to='be_streamvibe.movie'),
        ),
    ]
