# Generated by Django 5.0.4 on 2024-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0007_language_movie_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upcoming_movie',
            field=models.DateField(null=True),
        ),
    ]
