# Generated by Django 5.0.4 on 2024-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0008_movie_upcoming_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='upcoming_movie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
