# Generated by Django 5.0.4 on 2024-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0010_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='be_streamvibe.actor'),
        ),
    ]
