# Generated by Django 5.0.4 on 2024-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0012_musiccreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='music_creators',
            field=models.ManyToManyField(to='be_streamvibe.musiccreator'),
        ),
    ]
