# Generated by Django 4.2.13 on 2024-05-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0014_alter_faq_answer_support_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support_request',
            old_name='messages',
            new_name='message',
        ),
    ]
