# Generated by Django 4.2.13 on 2024-05-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0015_rename_messages_support_request_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=250)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be_streamvibe.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be_streamvibe.user')),
            ],
        ),
    ]
