# Generated by Django 5.0.4 on 2024-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0017_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='music_creators',
            field=models.ManyToManyField(to='be_streamvibe.musiccreator'),
        ),
    ]
