# Generated by Django 5.0.4 on 2024-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0019_alter_movie_duration_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(),
        ),
    ]
