# Generated by Django 5.0.4 on 2024-05-14 23:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0021_alter_rating_movie_alter_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='musiccreator',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
