# Generated by Django 5.0.4 on 2024-05-15 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0027_remove_rating_movie_remove_rating_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(default=datetime.date.today),
        ),
    ]
