# Generated by Django 5.0.4 on 2024-05-15 23:27

import be_streamvibe.models.movie
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0030_alter_movie_ratings_alter_movie_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=be_streamvibe.models.movie.get_current_year),
        ),
    ]
