# Generated by Django 5.0.4 on 2024-05-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0032_alter_movie_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, default=[], to='be_streamvibe.rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(blank=True, default=[], to='be_streamvibe.review'),
        ),
    ]
