# Generated by Django 5.0.4 on 2024-05-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0035_alter_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_url',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='trailer_url',
            new_name='trailer',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='trailer_thumbnail_url',
            new_name='trailer_thumbnail',
        ),
    ]
