# Generated by Django 5.0.4 on 2024-05-19 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0036_rename_movie_url_movie_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
