# Generated by Django 5.0.4 on 2024-05-19 19:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0037_alter_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_trailer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_thumbnail',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image_trailer'),
        ),
    ]
