# Generated by Django 5.0.4 on 2024-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0038_alter_movie_movie_alter_movie_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.TimeField(),
        ),
    ]
