# Generated by Django 5.0.4 on 2024-05-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0040_movie_release_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
