# Generated by Django 5.0.4 on 2024-05-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_streamvibe', '0042_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
